### PR TITLE
Make app not crash on Mojave

### LINKED ISSUE #46: Mac os 10.14 (Mojave) Beta
Can't open flashlight crashes on launch.

Stacktrace below:

`
Process:               Flashlight [73525]
Path:                  /private/var/folders/*/Flashlight.app/Contents/MacOS/Flashlight
Identifier:            com.nateparrott.Flashlight
Version:               1.0.8 (62)
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           Flashlight [73525]
User ID:               501

Date/Time:             2018-06-20 10:17:47.386 +0200
OS Version:            Mac OS X 10.14 (18A293u)
Report Version:        12
Bridge OS Version:     3.0 (14Y664)
Anonymous UUID:        AC305FE9-EDFC-B0C0-D329-5EC88BDFFA44

Sleep/Wake UUID:       CEE54AB4-9728-4B2C-80D3-74DF2E01864F

Time Awake Since Boot: 77000 seconds
Time Since Wake:       2700 seconds

System Integrity Protection: enabled

Notes:                 Translocated Process

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Application Specific Information:
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[__NSArrayM insertObject:atIndex:]: object cannot be nil'
terminating with uncaught exception of type NSException
abort() called

Application Specific Backtrace 1:
0   CoreFoundation                      0x00007fff2851e16a __exceptionPreprocess + 197
1   libobjc.A.dylib                     0x00007fff54447b10 objc_exception_throw + 48
2   CoreFoundation                      0x00007fff28554bdc -[CFPrefsConfigurationFileSource initWithConfigurationPropertyList:containingPreferences:] + 0
3   CoreFoundation                      0x00007fff28464a28 -[__NSArrayM insertObject:atIndex:] + 1216
4   AppKit                              0x00007fff25ae434b -[NSToolbarItemViewer configureForLayoutInDisplayMode:andSizeMode:inToolbarView:] + 1786
5   AppKit                              0x00007fff25ae21b4 -[NSToolbarView _layoutDirtyItemViewersAndTileToolbar] + 976
6   AppKit                              0x00007fff25b0e1cb -[NSToolbarView layout] + 54
7   AppKit                              0x00007fff262b4f50 _NSViewLayout + 587
8   AppKit                              0x00007fff25af0cfa -[NSView _layoutSubtreeWithOldSize:] + 446
9   AppKit                              0x00007fff25af0f73 -[NSView _layoutSubtreeWithOldSize:] + 1079
10  AppKit                              0x00007fff25af0f73 -[NSView _layoutSubtreeWithOldSize:] + 1079
11  AppKit                              0x00007fff25af0f73 -[NSView _layoutSubtreeWithOldSize:] + 1079
12  AppKit                              0x00007fff262bad50 -[NSView _layoutSubtreeIfNeededAndAllowTemporaryEngine:] + 1358
13  AppKit                              0x00007fff25b0d00b -[NSWindow(NSConstraintBasedLayout) _layoutViewTree] + 148
14  AppKit                              0x00007fff25b72797 -[NSWindow(NSConstraintBasedLayout) layoutIfNeeded] + 263
15  AppKit                              0x00007fff25b72678 -[NSWindow _setUpFirstResponderBeforeBecomingVisible] + 63
16  AppKit                              0x00007fff25b71b21 -[NSWindow _doWindowWillBeVisibleAsSheet:] + 157
17  AppKit                              0x00007fff262dbf8a -[NSWindow _reallyDoOrderWindowAboveOrBelow:relativeTo:findKey:forCounter:force:isModal:] + 1445
`

### PR DESCRIPTION
**Pull request by ThatsJustCheesy**
Closes #46. The crash was caused by some remnants of a toolbar checkbox that toggled plugins. The empty toolbar item really should not have caused a _crash_, but it didn't do anything anyway so it doesn't matter.

### CODE REVIEW

**Comment by w0lfschild** [comment]
I'll check this out of Friday and probably try to push an update out on Saturday. Thanks a ton for the PR.

**Comment by bachmx** [comment]
> I'll check this out of Friday and probably try to push an update out on Saturday. Thanks a ton for the PR.

Please update the app!

**Comment by TomEbert** [comment]
Please update the app I'd love being able to use it again :)

**Comment by sumanth-culli** [comment]
Yes please update the app.
@ThatsJustCheesy How to build the app from source after considering your commits? 
Or what files do I need to change in `/Applications/Flashlight.app/Contents`?

**Comment by w0lfschild** [comment]
@ThatsJustCheesy 

Thanks for the updates! I've added you to the credits in the readme.

@bachmx @TomEbert @duplex143 

Update is live but you'll have to manually download it as the app crashes before it can update on Mojave.

**Pull request merged**
